name: ultimate_movie_database
description: "Ultimate Movie Database"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.4
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  infinite_scroll_pagination: ^4.0.0
  lottie: ^2.7.0
  provider: ^6.1.1
  rename: ^3.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
    - assets/animations/

  uses-material-design: true
