name: ultimate_movie_database
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.4
  go_router: ^12.1.3
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
